### ISSUE TITLE
citekey containing colon not extracting?

### ISSUE THREAD

**Issue by michaelbroe** [sjpfenninger/citebibtex#11]
It appears that citekeys containing a colon [@Smith:1997] are not being extracted from my pandoc documents, whereas those which don't [@Smith1997] are being extracted succesfully.

The first form is autogenerated by my bibliography manager (Papers3).

**Comment by sjpfenninger** [comment]
I'll look into this and it should be easily fixed but expect it to take 1-2 weeks due to current business.

**Comment by michaelbroe** [comment]
Thanks, I appreciate it! The colon form is also one of the preset formats available for cite-key generation in BibDesk...
