### ISSUE TITLE
Additional fields for inserting reference

### ISSUE THREAD

**Issue by ldobl** [sjpfenninger/citebibtex#12]
It would be nice to add a few more possible fields (on top of `$CITATION`) to the styles for inserting references, when using citebibtex with files in which a plain text citation is required. 

For instance, it would be useful to use `"$AUTHOR: $TITLE ($YEAR)"` and similar patterns.

I managed to use some construction like `ref_authors = self.refs[self.current_ref_source][refid][1].split()[2]` and so on inside `insert_ref`, but it's quite a dirty thing, which does not work very well, and I can't seem to get many fields.

**Comment by sjpfenninger** [comment]
This is a good idea -- I added a basic implementation in 1.3.0, see the updated README.md, and let me know if issues/questions
