### ISSUE TITLE
Problems with non-ASCII bibliography files

### ISSUE THREAD

**Issue by twsh** [sjpfenninger/citebibtex#2]
If you have non-ASCII characters in the target bibliography file the script will fail. (I see a 'UnicodeDetectError' in the console.) I think this is because Sublime Text's version of Python doesn't get all the normal environment variables i.e. this happens even if normally Python would open the file correctly. I don't know whether this happens on all platforms. I'm using Yosemite.

I had the same issue with one of my plug-ins which I fixed simply by adding `encoding='UTF-8'` to my `open()` calls. I suppose that means that there would still be a problem if the user has some non-ASCII and non-UTF8 encoding. But I think that UTF-8 is recommended for Biblatex files for use with Pandoc.

**Comment by sjpfenninger** [comment]
You're right, this is a problem, I'll fix this and make it user-configurable with a default of UTF-8.
