### ISSUE TITLE
Bibpy library

### ISSUE THREAD

**Issue by twsh** [sjpfenninger/citebibtex#5]
The library you use for parsing has some quirks:

* Right quotation marks are deleted
* Spaces are inserted before commas in author names

I've had a good experience with [bibtexparser](https://github.com/sciunto-org/python-bibtexparser). A simple replacement for your `update_refs()` function would look like this (with BibTexParser having been loaded instead of pybib):
```
def update_refs(self, ref_file):
    with open(ref_file, 'r') as f:
        bib = BibTexParser(
            f.read(),
            ignore_nonstandard_types=False
        )
    refs = bib.entries_dict
    self.refs[ref_file] = [get_item(refs[i]) for i in refs]
```
By the way, this would also avoid the case problem because the output of bibtexparser has lower case keys. Otherwise it's identical to pybib for all the examples I've looked at.

**Comment by sjpfenninger** [comment]
Thanks for the suggestion! bibtexparser seems to be a cleaner library indeed. Switched in 956f523.
