### ISSUE TITLE
Package Control

### ISSUE THREAD

**Issue by twsh** [sjpfenninger/citebibtex#7]
The updates in the repo here don't seem to have made their way to Package Control here https://packagecontrol.io/packages/CiteBibtex. (I can use it fine from a cloned repo.)

**Comment by sjpfenninger** [comment]
You're right, I never pushed out a new release, thanks for the heads-up. Did that just now!

**Comment by twsh** [comment]
I've got it through package control now. It works well and I'm going to start using it instead of the system I had put together myself.

**Comment by sjpfenninger** [comment]
Glad to hear!
