### ISSUE TITLE
Non-blocking parse?

### ISSUE THREAD

**Issue by reagle** [sjpfenninger/citebibtex#8]
Howdy, I've always wanted something like this in a text editor and stumbled across this one recently. Thanks for creating this. It's much faster than a different one I tried but the trouble is my bibtex file is big (3.5M) which takes a while to parse. Hence, when I launch ST3, it takes about 1.5 seconds before I can start editing/moving in the document. I'm assuming that's the parsing. Do you know if there's a way to do the parse in the background?

**Comment by sjpfenninger** [comment]
My BibTeX files are significantly smaller so I haven't noticed this, but you are right, parsing should not block the editor. Should be straightforward to load the bibliography file asynchronously, since ST3 provides an asynchronous API anyway. I'll have a look at this!

**Comment by reagle** [comment]
Great, thank you!

**Comment by sjpfenninger** [comment]
Can you check whether the current master version on GitHub solves this for you? I think adding this to your Package Control settings, then uninstalling and reinstalling the package, should cause it to be fetched from GitHub instead of the regular package channel:

```
"repositories":
    [
        "https://github.com/sjpfenninger/citebibtex"
    ]
```

**Comment by sjpfenninger** [comment]
This is now in v1.2.1, closing this issue, let me know if there are problems

**Comment by reagle** [comment]
It looks like I installed v1.2.1 from package control and still have the delay?
